services:

  # MySQL
  mysql:
    image: mysql:8.0.34
    container_name: mysqldb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./MedilaboSolutions/ms-backend-patient/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: medilabo_patients
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: app_user
      MYSQL_PASSWORD: rootroot
    networks:
      - MedilaboSolutionNetworks

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medilabo_notes
    volumes:
      - mongo-data:/data/db
      - ./MedilaboSolutions/ms-notes/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - MedilaboSolutionNetworks

  # ms-backend-patient microservice
  ms-backend-patient:
    build:
      context: ./MedilaboSolutions/ms-backend-patient
      dockerfile: Dockerfile
    container_name: ms-backend-patient
    restart: always
    ports:
      - "8080:8080"
    depends_on:
       - mysql
    environment:
      MYSQL_URL: jdbc:mysql://mysqldb:3306/medilabo_patients?serverTimezone=UTC
      MYSQL_USER: app_user
      MYSQL_PASSWORD: rootroot
      MYSQL_PORT: '3306'
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
    networks:
      - MedilaboSolutionNetworks

  # ms-notes microservice
  ms-notes:
    build:
      context: ./MedilaboSolutions/ms-notes
      dockerfile: Dockerfile
    container_name: ms-notes
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: '27017'
      MONGO_DATABASE: medilabo_notes
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
    networks:
      - MedilaboSolutionNetworks

  # ms-diabetes-risk microservice
  ms-diabetes-risk:
    build:
      context: ./MedilaboSolutions/ms-diabetes-risk
      dockerfile: Dockerfile
    container_name: ms-diabetes-risk
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - ms-backend-patient
      - ms-notes
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
    networks:
      - MedilaboSolutionNetworks   

  # ms-gateway microservice
  ms-gateway:
    build:
      context: ./MedilaboSolutions/ms-gateway
      dockerfile: Dockerfile
    container_name: ms-gateway
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
    networks:
      - MedilaboSolutionNetworks

  # ms-frontend user interface Angular app
  ms-frontend:
    build:
      context: ./MedilaboSolutions/ms-frontend
      dockerfile: Dockerfile
    container_name: ms-frontend
    ports:
      - "4200:80"
    depends_on:
      - ms-gateway

volumes:
  mysql_data:
  mongo-data:

networks:
  MedilaboSolutionNetworks:
    driver: bridge