version: '3.8'

services:

  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - MedilaboSolutionNetworks

  # ms-backend-patient microservice
  ms-backend-patient:
    build:
      context: ./MedilaboSolutions/ms-backend-patient
      dockerfile: Dockerfile
    container_name: ms-backend-patient
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://michellerkmairet:jexya7JvqHpoZAJM@medilabocluster.ejx4f.mongodb.net/medilabo?retryWrites=true&w=majority&appName=MedilaboCluster
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
    depends_on:
      - mongodb
    networks:
      - MedilaboSolutionNetworks

  # ms-notes microservice
  ms-notes:
    build:
      context: ./MedilaboSolutions/ms-notes
      dockerfile: Dockerfile
    container_name: ms-notes
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://notes_user:secure_password@medilabocluster.ejx4f.mongodb.net/?retryWrites=true&w=majority&appName=MedilaboCluster
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
    depends_on:
      - mongodb
    networks:
      - MedilaboSolutionNetworks

  # ms-diabetes-risk microservice
  ms-diabetes-risk:
    build:
      context: ./MedilaboSolutions/ms-diabetes-risk
      dockerfile: Dockerfile
    container_name: ms-diabetes-risk
    ports:
      - "8084:8084"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
    depends_on:
      - ms-backend-patient
      - ms-notes
    networks:
      - MedilaboSolutionNetworks   

  # ms-gateway microservice
  ms-gateway:
    build:
      context: ./MedilaboSolutions/ms-gateway
      dockerfile: Dockerfile
    container_name: ms-gateway
    ports:
      - "8082:8082"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
    networks:
      - MedilaboSolutionNetworks

  # ms-frontend user interface Angular app
  ms-frontend:
    build:
      context: ./MedilaboSolutions/ms-frontend
      dockerfile: Dockerfile
    container_name: ms-frontend
    ports:
      - "4200:80"
    depends_on:
      - ms-gateway
    environment:
      API_GATEWAY_URL: http://ms-gateway:8082/api
      AUTH_URL: http://ms-gateway:8082/api/auth
      PATIENTS_SERVICE_URL: http://ms-gateway:8082/api/patients
      NOTES_SERVICE_URL: http://ms-gateway:8082/api/notes
      RISK_SERVICE_URL: http://ms-gateway:8082/api/risk

volumes:
  mongo-data:

networks:
  MedilaboSolutionNetworks:
    driver: bridge