version: '3.8'

services:
  ms-backend-patient:
    build:
      context: ./MedilaboSolutions/ms-backend-patient
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://michellerkmairet:jexya7JvqHpoZAJM@medilabocluster.ejx4f.mongodb.net/medilabo?retryWrites=true&w=majority&appName=MedilaboCluster
    depends_on:
      - mongodb-patient

  ms-notes:
    build:
      context: ./MedilaboSolutions/ms-notes
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://notes_user:secure_password@medilabocluster.ejx4f.mongodb.net/?retryWrites=true&w=majority&appName=MedilaboCluster
    depends_on:
      - mongodb-notes

  ms-diabetes-risk:
    build:
      context: ./MedilaboSolutions/ms-diabetes-risk
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082

  ms-gateway:
    build:
      context: ./MedilaboSolutions/ms-gateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://ms-gateway:8082
      AUTH_USERNAME: user
      AUTH_PASSWORD: $2a$10$e3DcyuLgiltgq/uU2zZwA.Fg.ezp6T4LSMC1fySCkbL6XIQZ1Gn0a
      SECURITY_JWT_SECRET: VZt6BknY0azyGkSvLF1ve/2Vq1QBf67dniofFr/Q6hs=

  ms-frontend:
    build:
      context: ./MedilaboSolutions/ms-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  mongodb-patient:
    image: mongo:latest
    container_name: mongodb-patient
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medilabo
      MONGO_INITDB_ROOT_USERNAME: michellerkmairet
      MONGO_INITDB_ROOT_PASSWORD: jexya7JvqHpoZAJM

  mongodb-notes:
    image: mongo:latest
    container_name: mongodb-notes
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: medilabo_notes
      MONGO_INITDB_ROOT_USERNAME: notes_user
      MONGO_INITDB_ROOT_PASSWORD: secure_password

networks:
  default:
    driver: bridge
